### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by TheSriram**
Add python tags to the readme

### CODE REVIEW

**Comment by avinassh** [comment]
Hey, thanks for the PR. It is adding extra indentations in README. It would make copy-paste not easier

**Comment by TheSriram** [comment]
yes, but you get colors lol.

Feel free to close it.

**Comment by avinassh** [comment]
I agree withe colors and it looks great. but extra indentation is turning me off

**Comment by Socialery** [comment]
@TheSriram you can de-indent the text in the ``` blocks

    ```python
    print("test")
    ```

becomes

```python
print("test")
```

**Comment by avinassh** [comment]
check this @TheSriram 

https://github.com/avinassh/rockstar/blob/master/README.md

**Comment by TheSriram** [comment]
I need to squash this.

**Comment by avinassh** [comment]
Merged! No need of squashing when commits are only 2. plus this library is not committed that often 

:beers:

**Pull request merged**
